#:schema ../../node_modules/wrangler/config-schema.json

name = "surge-geosite-panel"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2026-03-02"
workers_dev = true
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "surge.bojin.co/*", zone_name = "bojin.co" }
]

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[[services]]
binding = "GEOSITE_API"
service = "surge-geosite"
