#:schema ../../node_modules/wrangler/config-schema.json

name = "surge-geosite-panel"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2026-03-02"
compatibility_flags = ["nodejs_compat"]

[[services]]
binding = "GEOSITE_API"
service = "surge-geosite"
